env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:wc/recommended
  - plugin:lit/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - 'wc'
  - 'lit'
